const Router = require('express')
const router = new Router()
const projectBibleTemplateController = require('../controller/projectBibleTemplate.controller')

//Запросы к таблице project_bible_template
router.get('/projectBibleTemplate', projectBibleTemplateController.getProjectBibleTemplates)
router.get('/projectBibleTemplateGenerateIndividualCode', projectBibleTemplateController.projectBibleTemplateGenerateIndividualCode)
router.post('/projectBibleTemplateAddColumnToTheEnd', projectBibleTemplateController.setProjectBibleTemplateAddColumnToTheEnd)
router.post('/projectBibleTemplateAddColumn', projectBibleTemplateController.setProjectBibleTemplateAddColumn)
router.post('/projectBibleTemplateIncNumPredAddColumn', projectBibleTemplateController.setProjectBibleTemplateIncNumPredAddColumn)
router.post('/projectBibleTemplateUpdateColumnTemplate', projectBibleTemplateController.projectBibleTemplateUpdateColumnTemplate)
router.post('/projectBibleTemplateMoveUpColumn', projectBibleTemplateController.setProjectBibleTemplateMoveUpColumn)
router.post('/projectBibleTemplateMoveDownColumn', projectBibleTemplateController.setProjectBibleTemplateMoveDownColumn)
router.post('/projectBibleTemplateDecNumPredDeleteColumn', projectBibleTemplateController.setProjectBibleTemplateDecNumPredDeleteColumn)
router.post('/projectBibleTemplateDeleteColumn', projectBibleTemplateController.setProjectBibleTemplateDeleteColumn)
router.post('/projectBibleColumnsForClientTemplate', projectBibleTemplateController.getProjectBibleColumnsForClientTemplate)

//Запросы к таблице project_bible_template_tags
router.get('/projectBibleTemplateTags', projectBibleTemplateController.getProjectBibleTemplateTags)
router.get('/projectBibleTemplateGenerateTagGroupIndividualCode', projectBibleTemplateController.projectBibleTemplateGenerateTagGroupIndividualCode)
router.post('/projectBibleTemplateTagsAddGroupTag', projectBibleTemplateController.setProjectBibleTemplateTagsAddGroupTag)
router.post('/projectBibleTemplateTagsUpdateGroupTag', projectBibleTemplateController.setProjectBibleTemplateTagsUpdateGroupTag)
router.post('/projectBibleTemplateDecNumPredDeleteTagGroup', projectBibleTemplateController.setProjectBibleTemplateDecNumPredDeleteTagGroup)
router.post('/projectBibleTemplateTagsDeleteGroupTag', projectBibleTemplateController.setProjectBibleTemplateTagsDeleteGroupTag)
router.get('/projectBibleTemplateGenerateTagIndividualCode', projectBibleTemplateController.projectBibleTemplateGenerateTagIndividualCode)
router.post('/projectBibleTemplateTagsAddTag', projectBibleTemplateController.setProjectBibleTemplateTagsAddTag)
router.post('/projectBibleTemplateTagsUpdateTag', projectBibleTemplateController.setProjectBibleTemplateTagsUpdateTag)
router.post('/projectBibleTemplateTagsDeleteTag', projectBibleTemplateController.setProjectBibleTemplateTagsDeleteTag)
// router.post('/projectBibleTemplateTagsCheckExistBeforeUpdateTag', projectBibleTemplateController.setProjectBibleTemplateTagsCheckExistBeforeUpdateTag)

//Запросы к таблице project_bible_template && project_bible_template_rows
router.post('/projectBibleTemplateRowsColumns', projectBibleTemplateController.getProjectBibleColumnsRowsTemplate)
router.post('/projectBibleTemplateActiveRowsAndColumnsWithTemplate', projectBibleTemplateController.getProjectBibleActiveColumnsWithTemplateAndRows)

//Запросы к таблице project_bible_template_rows
router.get('/projectBibleTemplateGenerateRowIndividualCode', projectBibleTemplateController.projectBibleTemplateGenerateRowIndividualCode)
router.post('/projectBibleTemplateAddRowToTheEnd', projectBibleTemplateController.setProjectBibleTemplateAddRowToTheEnd)
router.post('/projectBibleTemplateIncNumPredAddRow', projectBibleTemplateController.setProjectBibleTemplateIncNumPredAddRow)
router.post('/projectBibleTemplateAddRow', projectBibleTemplateController.setProjectBibleTemplateAddRow)
router.post('/projectBibleTemplateDecNumPredDeleteRow', projectBibleTemplateController.setProjectBibleTemplateDecNumPredDeleteRow)
router.post('/projectBibleTemplateDeleteRow', projectBibleTemplateController.setProjectBibleTemplateDeleteRow)
router.post('/projectBibleTemplateMoveUpRow', projectBibleTemplateController.setProjectBibleTemplateMoveUpRow)
router.post('/projectBibleTemplateMoveDownRow', projectBibleTemplateController.setProjectBibleTemplateMoveDownRow)

//Запросы к таблице project_bible_template_text
router.post('/projectBibleTemplateTextByName', projectBibleTemplateController.getProjectBibleTextTemplateValue)
router.post('/projectBibleTemplateTextByNameIfExist', projectBibleTemplateController.getProjectBibleTextTemplateIfExistValue)
router.post('/projectBibleTemplateOninputUpdateTextCell', projectBibleTemplateController.setProjectBibleTemplateOninputUpdateTextCell)
router.post('/projectBibleTemplateOninputInsertTextCell', projectBibleTemplateController.setProjectBibleTemplateOninputInsertTextCell)

//Запросы к таблице project_bible_template_bool
router.post('/projectBibleTemplateBoolByName', projectBibleTemplateController.getProjectBibleBoolTemplateValue)
router.post('/projectBibleTemplateBoolByNameIfExist', projectBibleTemplateController.getProjectBibleBoolTemplateIfExistValue)
router.post('/projectBibleTemplateOninputUpdateBoolCell', projectBibleTemplateController.setProjectBibleTemplateOninputUpdateBoolCell)
router.post('/projectBibleTemplateOninputInsertBoolCell', projectBibleTemplateController.setProjectBibleTemplateOninputInsertBoolCell)

//Запросы к таблице project_bible_template_json
router.post('/projectBibleTemplateTagJsonByName', projectBibleTemplateController.getProjectBibleTagJsonTemplateValue)
router.post('/projectBibleTemplateTagJsonByNameIfExist', projectBibleTemplateController.getProjectBibleTagJsonTemplateIfExistValue)
router.post('/projectBibleTemplateUpdateTagJsonCell', projectBibleTemplateController.setProjectBibleTemplateUpdateTagJsonCell)
router.post('/projectBibleTemplateInsertTagJsonCell', projectBibleTemplateController.setProjectBibleTemplateInsertTagJsonCell)

//Запросы к таблице project_bible_info
router.post('/projectBibleInfo', projectBibleTemplateController.getProjectBibleInfo)
router.post('/projectBibleInfoInsert', projectBibleTemplateController.setProjectBibleInfoInsert)
router.post('/projectBibleInfoMoveUpRow', projectBibleTemplateController.setProjectBibleInfoMoveUpRow)
router.post('/projectBibleInfoMoveDownRow', projectBibleTemplateController.setProjectBibleInfoMoveDownRow)

//Запросы к таблице project_bible_text
router.post('/projectBibleFilledCellTextByName', projectBibleTemplateController.getProjectBibleTextGetCellValue)
router.post('/projectBibleOninputUpdateTextCell', projectBibleTemplateController.setProjectBibleOninputUpdateTextCell)
router.post('/projectBibleOninputInsertTextCell', projectBibleTemplateController.setProjectBibleOninputInsertTextCell)

//Запросы к таблице project_bible_bool
router.post('/projectBibleFilledCellBoolByName', projectBibleTemplateController.getProjectBibleBoolGetCellValue)
router.post('/projectBibleOninputUpdateBoolCell', projectBibleTemplateController.setProjectBibleOninputUpdateBoolCell)
router.post('/projectBibleOninputInsertBoolCell', projectBibleTemplateController.setProjectBibleOninputInsertBoolCell)

//Запросы к таблице project_bible_client_view
router.get('/projectBibleClientViewGenerateIndividualCode', projectBibleTemplateController.projectBibleClientViewGenerateIndividualCode)
router.post('/projectBibleClientViewInsert', projectBibleTemplateController.setProjectBibleClientViewInsert)
router.post('/projectBibleClientView', projectBibleTemplateController.getProjectBibleClientView)
router.post('/projectBibleClientViewByCode', projectBibleTemplateController.getProjectBibleClientViewByCode)
router.post('/projectBibleClientViewDelete', projectBibleTemplateController.setProjectBibleClientViewDelete)
router.post('/createProjectBiblePdf', projectBibleTemplateController.setCreateProjectBiblePdf)
router.post('/projectBibleClientViewSubmit', projectBibleTemplateController.setProjectBibleClientViewSubmit)

//Запросы к таблице project_bible_client_view_text
router.post('/projectBibleClientViewFilledCellTextByName', projectBibleTemplateController.getProjectBibleClientViewTextGetCellValue)
router.post('/projectBibleClientViewOninputUpdateTextCell', projectBibleTemplateController.setProjectBibleClientViewOninputUpdateTextCell)
router.post('/projectBibleClientViewOninputInsertTextCell', projectBibleTemplateController.setProjectBibleClientViewOninputInsertTextCell)

//Запросы к таблице project_bible_client_view_bool
router.post('/projectBibleClientViewFilledCellBoolByName', projectBibleTemplateController.getProjectBibleClientViewBoolGetCellValue)
router.post('/projectBibleClientViewOninputUpdateBoolCell', projectBibleTemplateController.setProjectBibleClientViewOninputUpdateBoolCell)
router.post('/projectBibleClientViewOninputInsertBoolCell', projectBibleTemplateController.setProjectBibleClientViewOninputInsertBoolCell)







// router.post('/projectBibleTemplate', projectBibleTemplateController.createProjectBibleTemplate)
// router.get('/projectBibleTemplate', projectBibleTemplateController.getProjectBibleTemplates)
// router.get('/projectBibleTemplate/:name', projectBibleTemplateController.getOneProjectBibleTemplate)
// router.put('/projectBibleTemplate', projectBibleTemplateController.updateProjectBibleTemplate)
// router.delete('/projectBibleTemplate/:name', projectBibleTemplateController.deleteProjectBibleTemplate)

router.get('/projectBibleTemplateText', projectBibleTemplateController.getProjectBibleTemplatesText)

// router.post('/projectBibleTemplateTextByName', projectBibleTemplateController.getProjectBibleTemplateTextByName)
// router.post('/projectBibleTemplateBoolByName', projectBibleTemplateController.getProjectBibleTemplateBoolByName)

router.post('/projectBibleOninputPredSave', projectBibleTemplateController.predSetProjectBibleOninputSave)
router.post('/projectBibleOninputInsertRow', projectBibleTemplateController.predSetProjectBibleOninputInsertSave)
router.post('/projectBibleOninputUpdateRow', projectBibleTemplateController.predSetProjectBibleOninputUpdateSave)

router.post('/projectBibleGetFilledCells', projectBibleTemplateController.getProjectBibleFilledCell)

module.exports = router